config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "localhost"

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  ActiveAdmin.routes(self)

  get 'vacancies/index'

  root 'candidates#index'

  resources :positions
  resources :criteria
  resources :candidates
  resources :vacancies
  resources :position_criterium_scores
  resources :candidate_criterium_scores

  get "home/statistics"


end

app/views/shared/_navigation_bar.html.erb
<div class="ui inverted large menu">


<div class="item">
    </div>

  <% if Vacancy.opened.count > 0 %>
      <div class="ui labeled button item" tabindex="0">
            <%= button_to  vacancies_path, method: "get", class: "ui red button" do %>
                <i class="users icon"></i> Вакансии
            <% end %>
      <a class="ui basic red left pointing label">
      <%= Vacancy.opened.count %>
      </a>
      </div>
  <% else %>
        <div class="ui labeled button item" tabindex="0">
              <%= button_to  vacancies_path, method: "get", class: "ui green button" do %>
                  <i class="users icon"></i> Вакансии
              <% end %>
        <a class="ui basic red left pointing label">
        <%= Vacancy.opened.count %>
        </a>
        </div>
  <% end %>

  <div class="item">
    <%= button_to  candidates_path, method: "get", class: "medium ui  secondary button" do %>
    <i class="user circle icon"></i>
      Кандидаты
    <% end %>
  </div>


  <div class="item">
    <%= button_to  positions_path, method: "get", class: "medium ui secondary button" do %>
      <i class="address card outline icon"></i>
      Должности
    <% end %>
  </div>

  <div class="item">
    <%= button_to  criteria_path, method: "get", class: "medium ui secondary button" do %>
      <i class="info icon"></i>
      Критерии
    <% end %>
  </div>


    <div class="right menu">

      <% if current_user.is_admin? %>
        <div class="item">
          <%= button_to  home_statistics_path,method: "get", class: "medium ui google plus button" do %>
            <i class="file alternate icon"></i>
            Статистика
          <% end %>
        </div>
      <% end %>



      <div class=" item">

        <% if current_user.is_admin? %>
        <div class="ui large buttons">

          <%= button_to  admin_root_path, method: "get", class: "ui button" do %>

            <i class="icon settings"></i>
            Админ
          <% end %>

          <div class="or"></div>

          <%= button_to  destroy_user_session_path, method: "delete", class: "ui button" do %>

            <i class="sign out alternate icon"></i>
                        Выйти
          <% end %>

        </div>
        <% else %>

          <%= button_to  destroy_user_session_path, method: "delete", class: "ui right labeled icon button" do %>

            <i class="sign out alternate icon"></i>
                        Выйти
          <% end %>


        <%  end %>


      </div>

    </div>

</div>